# -*- coding: utf-8 -*-
"""Sigma_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_dKwAvzZbOEz5ibEubnbwOLcyzAWyj7e
"""

# Chatbot greeting
def greet_user():
    print("Hello! I am Sigma – your friendly financial sidekick!")
    print("I help you pick the best crypto based on trends and sustainability. \n")

greet_user()

# Predefined cryptocurrency database
crypto_db = {
    "Bitcoin": {
        "price_trend": "rising",
        "market_cap": "high",
        "energy_use": "high",
        "sustainability_score": 3
    },
    "Ethereum": {
        "price_trend": "stable",
        "market_cap": "high",
        "energy_use": "medium",
        "sustainability_score": 6
    },
    "Cardano": {
        "price_trend": "rising",
        "market_cap": "medium",
        "energy_use": "low",
        "sustainability_score": 8
    }
}

def get_crypto_advice(user_query):
    query = user_query.lower()

    if "sustainable" in query:
        recommend = max(crypto_db, key=lambda x: crypto_db[x]["sustainability_score"])
        print(f" Invest in {recommend}! It is eco-friendly and has long-term potential.")

    elif "trending" in query or "rising" in query:
        trending = [coin for coin in crypto_db if crypto_db[coin]["price_trend"] == "rising"]
        print(f" These cryptos are trending up: {', '.join(trending)}")

    elif "long-term" in query or "best" in query:
        for coin, data in crypto_db.items():
            if data["price_trend"] == "rising" and data["sustainability_score"] > 7:
                print(f" Go with {coin}! It is growing and sustainable.")
                return
        print(" No ideal match found for long-term investment right now.")

    else:
        print(" I am not sure how to help with that. Try asking about trends or sustainability.")

# Include disclaimer at the end of each response
    print("\n Disclaimer: Crypto is risky—always do your own research!")

# Test the chatbot with sample queries
get_crypto_advice("Which crypto is trending up?")
get_crypto_advice("What’s the most sustainable coin?")
get_crypto_advice("Which crypto should I buy for long-term growth?")

while True:
    user_input = input("\nYou: ")
    if user_input.lower() in ["exit", "quit"]:
        print("Sigma: Bye for now!")
        break
    get_crypto_advice(user_input)